#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_XCCONFIG="$ROOT/Config/Branchlight.local.xcconfig"
APP_PATH="${BRANCHLIGHT_SIGNED_APP_PATH:-/Applications/Branchlight.app}"
TEAM_ID="${BRANCHLIGHT_DEVELOPMENT_TEAM:-${1:-}}"

detect_from_app() {
  local app="$1"
  [[ -d "$app" ]] || return 1
  codesign -dvvv "$app" 2>&1 | sed -n 's/^TeamIdentifier=//p' | head -n 1
}

detect_from_identities() {
  security find-identity -v -p codesigning 2>/dev/null \
    | sed -nE 's/.*\(([A-Z0-9]{10})\).*/\1/p' \
    | sort -u
}

if [[ -z "$TEAM_ID" ]]; then
  TEAM_ID="$(detect_from_app "$APP_PATH" || true)"
fi

if [[ -z "$TEAM_ID" ]]; then
  IDENTITIES=()
  while IFS= read -r identity; do
    [[ -n "$identity" ]] && IDENTITIES+=("$identity")
  done < <(detect_from_identities || true)
  if [[ "${#IDENTITIES[@]}" -eq 1 ]]; then
    TEAM_ID="${IDENTITIES[0]}"
  elif [[ "${#IDENTITIES[@]}" -gt 1 ]]; then
    echo "Multiple Apple Development teams are installed:" >&2
    printf '  %s\n' "${IDENTITIES[@]}" >&2
    echo "Re-run with: bash scripts/configure-development-signing.sh <TEAM_ID>" >&2
    exit 65
  fi
fi

if [[ ! "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
  echo "Could not determine a valid 10-character Apple Development Team ID." >&2
  echo "Set BRANCHLIGHT_DEVELOPMENT_TEAM or pass the Team ID as the first argument." >&2
  exit 64
fi

mkdir -p "$(dirname "$LOCAL_XCCONFIG")"
cat > "$LOCAL_XCCONFIG" <<EOF
// Local-only Branchlight development signing settings.
// Generated by scripts/configure-development-signing.sh
DEVELOPMENT_TEAM = $TEAM_ID
CODE_SIGN_STYLE = Automatic
REGISTER_APP_GROUPS = YES
EOF

echo "Configured Branchlight development signing for Team $TEAM_ID"
echo "Local config: $LOCAL_XCCONFIG"
echo "Next: xcodegen generate"
